export const optionsTugas = [
    "Puskesmas Cilandak",
    "PUSTU Pondok Labu",
    "PUSTU Cilandak Barat",
    "PUSTU Lebak Bulus",
    "PUSTU Gandaria Selatan",
    "PUSTU Cipete Selatan",
  ];

  export const optionBulanPelaksanaan = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
  ]
  
  export const optionPokja = ["Admen", "UKP", "UKM"];
  export const optionKegiatan = [
    "Peningkatan Pelayanan BLUD",
    "Penyediaan Layanan Kesehatan untuk UKP Rujukan, UKM dan UKM Rujukan Tingkat Daerah Provinsi",
    "Pengelolaan Pelayanan Kesehatan Dasar Melalui Pendekatan KeluargaPenyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota",
    "Perencanaan Kebutuhan dan Pendayagunaan Sumber Daya Manusia Kesehatan untuk UKP dan UKM di Wilayah Kabupaten/Kota",
    "Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM) Tingkat Daerah Kabupaten/Kota",
  ];
  export const optionSubKegiatan = [
    "Pelayanan dan Penunjang Pelayanan BLUD",
    "Pembinaan Pelaksanaan Upaya Pelayanan Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Dasar Melalui Pendekatan Keluarga",
    "Pengelolaan Pelayanan Kesehatan Ibu Hamil",
    "Pengelolaan Pelayanan Kesehatan Ibu Bersalin",
    "Pengelolaan Pelayanan Kesehatan Bayi Baru Lahir",
    "Pengelolaan Pelayanan Kesehatan Balita",
    "Pengelolaan Pelayanan Kesehatan pada Usia Pendidikan Dasar",
    "Pengelolaan Pelayanan Kesehatan pada Usia Produktif",
    "Pengelolaan Pelayanan Kesehatan pada Usia Lanjut",
    "Pengelolaan Pelayanan Kesehatan Penderita Hipertensi",
    "Pengelolaan Pelayanan Kesehatan Penderita Diabetes Melitus",
    "Pengelolaan Pelayanan Kesehatan Orang dengan Gangguan Jiwa Berat",
    "Pengelolaan Pelayanan Kesehatan Orang Terduga Tuberkulosis",
    "Pengelolaan Pelayanan Kesehatan Orang dengan Risiko Terinfeksi HIV",
    "Pengelolaan Pelayanan Kesehatan Gizi Masyarakat",
    "Pengelolaan Pelayanan Kesehatan Kerja dan Olahraga",
    "Pengelolaan Pelayanan Kesehatan Lingkungan",
    "Pengelolaan Pelayanan Promosi Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Tradisonal, Akupuntur, Asuhan Mandiri dan Tradisional Lainnya",
    "Pengelolaan Surveilans Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Penyakit Menular dan Tidak Menular",
    "Pengelolaan pelayanan kesehatan orang dengan Tuberkulosis",
    "Pengelolaan pelayanan kesehatan orang dengan HIV (ODHIV)",
    "Pengelolaan pelayanan kesehatan Malaria",
    "Pengelolaan Kawasan tanpa rokok",
    "Pengelolaan Pelayanan Kesehatan Haji",
    "Pemenuhan Kebutuhan Sumber Daya Manusia Kesehatan Sesuai Standar",
    "Bimbingan Teknis dan Supervisi Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM)",
  ];
  export const optionKomponen = ["Makan", "Snack", "Transport", "honor"];
  export const optionIndikatorKinerja = [
    "Jumlah  Alat  Kesehatan/Alat  Penunjang  Medik Fasilitas Layanan Kesehatan yang Disediakan",
    "Jumlah  Alat  Kesehatan/Alat  Penunjang  Medik Fasilitas   Layanan   Kesehatan   yang   Terpelihara Sesuai Standar",
    "Jumlah Sarana, Prasarana dan Alat Kesehatan yang Telah Dilakukan Rehabilitasi dan Pemeliharaan Oleh Puskesmas",
    "Jumlah Ibu Hamil yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Ibu Bersalin yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Bayi Baru Lahir yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Balita yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Anak Usia Pendidikan Dasar yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penduduk Usia Produktif yangMendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penduduk Usia Lanjut yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penderita Hipertensi yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penderita Diabetes Melitus yangMendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Orang yang Mendapatkan PelayananKesehatan Orang dengan Gangguan Jiwa Berat Sesuai Standar",
    "Jumlah Orang Terduga Menderita Tuberkulosis yang Mendapatkan Pelayanan Sesuai Standar",
    "Jumlah Orang Terduga Menderita HIV yang Mendapatkan Pelayanan Sesuai Standar",
    "Jumlah Fasilitas Kesehatan yang Terakreditasi diKabupaten/Kota",
    "Jumlah Dokumen Hasil Pengelolaan Sistem Informasi Kesehatan",
    "Jumlah Sumber Daya Manusia Kesehatan Kompetensi dan Kualifikasi Meningkat",
    "Jumlah Sumber Daya Manusia Kesehatan yang Memenuhi Standar di Fasilitas Pelayanan Kesehatan (Fasyankes)",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Perizinan Apotek, Toko Obat, Toko Alat Kesehatan, dan Optikal, Usaha Mikro ObatTradisional (UMOT)",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Sertifikat Produksi Pangan Industri Rumah Tangga dan Nomor P-IRT sebagai Izin Produksi, untuk Produk Makanan Minuman Tertentu yang Dapat Diproduksi oleh Industri Rumah Tangga",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Penerbitan Sertifikat Laik Higiene Sanitasi Tempat Pengelolaan Makanan (TPM) antara lain Jasa Boga, Rumah Makan/Restoran dan Depot Air Minum (DAM)",
    "Jumlah Dokumen Hasil Bimbingan Teknis dan Supervisi Upaya Kesehatan Bersumber Daya Masyarakat (UKBM)",
    "Jumlah Dokumen Perencanaan Perangkat Daerah",
    "Jumlah Laporan Evaluasi Kinerja Perangkat Daerah",
    "Jumlah Laporan Keuangan Akhir Tahun SKPD dan Laporan Hasil Koordinasi Penyusunan Laporan Keuangan Akhir Tahun SKPD",
    "Jumlah Pegawai Berdasarkan Tugas dan Fungsi yang Mengikuti Pendidikan dan Pelatihan",
    "Jumlah Paket Peralatan dan Perlengkapan Kantoryang Disediakan",
    "Jumlah Paket Barang Cetakan dan Penggandaan yang Disediakan",
    "Jumlah Paket Bahan/Material yang Disediakan",
    "Jumlah Laporan Fasilitasi Kunjungan Tamu",
    "Jumlah Laporan Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD",
    "Jumlah Laporan Penyediaan Jasa Komunikasi, Sumber Daya Air dan Listrik yang Disediakan",
    "Jumlah Laporan Penyediaan Jasa Peralatan danPerlengkapan Kantor yang Disediakan",
    "Jumlah Laporan Penyediaan Jasa PelayananUmum Kantor yang Disediakan",
    "Jumlah Kendaraan Dinas Operasional atau Lapangan yang Dipelihara dan Dibayarkan Pajak dan Perizinannya",
    "Jumlah Peralatan dan Mesin Lainnya yang Dipelihara",
    "Jumlah BLUD yang Menyediakan Pelayanan dan Penunjang Pelayanan",
    "Jumlah Dokumen Hasil Pengelolaan Pelayanan Kesehatan Lingkungan"
  ];
  export const optionSumberPembiayaan = ["APBD", "BLUD"];

  export const optionAktivitas = [
    "Belanja Barang dan Jasa BLUD",
    "Belanja Modal Peralatan dan Mesin BLUD",
    "Belanja Modal Gedung dan Bangunan BLUD",
    "Sosialisasi Internal Puskesmas dan Pustu tentang Integrasi Pelayanan Kesehatan Primer (ILP)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Gandaria Selatan)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Cipete Selatan)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Cilandak Barat)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Lebak Bulus)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Pondok Labu)",
    "Jejaring Fasyankes",
    "Peningkatan IKS di Wilayah Prioritas (Gandaria Selatan)",
    "Peningkatan IKS di Wilayah Prioritas (Cipete Selatan)",
    "Peningkatan IKS di Wilayah Prioritas (Cilandak Barat)",
    "Peningkatan IKS di Wilayah Prioritas (Lebak Bulus)",
    "Peningkatan IKS di Wilayah Prioritas (Pondok Labu)",
    "Optimalisasi Pelaksanaan KTR di Wilayah Kampung bebas Asap Rokok Kecamatan Cilandak",
    "Penyediaan Buku KIA",
    "Kelas Ibu Hamil (Gandaria Selatan)",
    "Kelas Ibu Hamil (Cipete Selatan)",
    "Kelas Ibu Hamil (Cilandak Barat)",
    "Kelas Ibu Hamil Luwes (Lebak Bulus)",
    "Kelas Ibu Hamil (Pondok Labu)",
    "Kelas Ibu Hamil Cemerlang (Gandaria Selatan)",
    "Kelas Ibu Hamil Cemerlang (Pondok Labu)",
    "Kelas Ibu Hamil Cemerlang (Cipete Selatan)",
    "Kelas Ibu Hamil Cemerlang (Cilandak Barat)",
    "Kelas Ibu Hamil Cemerlang (Lebak Bulus)",
    "Kelas Ibu Hamil (Puskesmas Cilandak)",
    "Supervisi Fasilitatif Fasyankes KIA (Gandaria Selatan)",
    "Supervisi Fasilitatif Fasyankes KIA (Cipete Selatan)",
    "Supervisi Fasilitatif Fasyankes KIA (Cilandak Barat)",
    "Supervisi Fasilitatif Fasyankes KIA (Lebak Bulus)",
    "Supervisi Fasilitatif Fasyankes KIA (Pondok Labu)",
    "Peningkatan Kemampuan dalam Menangani Kegawatdaruratan di RB",
    "Kelas Persiapan Persalinan dan Tour Rumah Bersalin",
    "Audit Kematian Maternal Perinatal",
    "Pemeriksaan Skrining Hipotiroid Kongenital (SHK)",
    "Refreshing Wawasan SDIDTK pada Kader Posyandu (Pondok Labu)",
    "Kelas Balita Disabilitas",
    "Pedas (Pengasuh Cerdas) (Lebak Bulus)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Gandaria Selatan)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Cipete Selatan)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Cilandak Barat)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Pondok Labu)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Lebak Bulus)",
    "Kelas Ibu Balita (Gandaria Selatan)",
    "Kelas Ibu Balita (Cipete Selatan)",
    "Kelas Ibu Balita (Lebak Bulus)",
    "Kelas Ibu Balita (Cilandak Barat)",
    "Rapat Koordinasi Kegiatan Pikumbang kepada Kepala Sekolah PAUD Wilayah Cilandak",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Cipete Selatan)",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Cilandak Barat)",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Lebak Bulus)",
    "Roadshow Kesehatan Mental pada Remaja (Gandaria Selatan)",
    "Roadshow Kesehatan Mental pada Remaja (Cipete Selatan)",
    "Roadshow Kesehatan Mental pada Remaja (Lebak Bulus)",
    "Roadshow Kesehatan Mental pada Remaja (Cilandak Barat)",
    "Roadshow Kesehatan Mental pada Remaja (Pondok Labu)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Gandaria Selatan)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Cipete Selatan)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Cilandak Barat)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Lebak Bulus)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Pondok Labu)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Gandaria Selatan)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Cipete Selatan)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Cilandak Barat)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Lebak Bulus)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Pondok Labu)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Lebak Bulus)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Cilandak Barat)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Gandaria Selatan)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Cipete Selatan)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Pondok Labu)",
    "Pelatihan Konselor Sebaya (Cipete Selatan)",
    "Sosialisasi Deteksi Dini Kanker Anak (Cipete Selatan)",
    "Peningkatan Wawasan tentang KBPP (Cipete Selatan)",
    "Peningkatan Wawasan tentang KBPP (Cilandak Barat)",
    "Peningkatan Wawasan tentang KBPP (Pondok Labu)",
    "Peningkatan Wawasan tentang KBPP (Lebak Bulus)",
    "Monitoring evaluasi posyandu remaja (Cipete Selatan)",
    "Peningkatan Wawasan tentang Anemia Remaja Putri, Cara Penanggulangannya, dan Program Tablet Tambah D (Lebak Bulus)",
    "Peningkatan Wawasan tentang Anemia Remaja Putri (Pondok Labu)",
    "Pembelian Strip Gula Darah",
    "Sosialisasi SKILAS dan PJP (Lebak Bulus)",
    "Sosialisasi SKILAS dan PJP (Pondok Labu)",
    "Sosialisasi SKILAS dan PJP (Cilandak Barat)",
    "Sosialisasi SKILAS dan PJP (Cipete Selatan)",
    "Sosialisasi SKILAS dan PJP (Gandaria Selatan)",
    "Peningkatan wawasan lansia \"Pencegahan Dementia pada lansia dengan senam otak\" (Lebak Bulus)",
    "Sosialisasi kader tentang caregriver (Cipete Selatan)",
    "Pelatihan Perawatan Jangka Panjang Bagi Caregiver (Puskesmas Cilandak)",
    "Konseling Jiwa Pada Lansia dengan Gangguan Depresi (Puskesmas Cilandak)",
    "Pembelian Strip Kolestrol",
    "Peningkatan Wawasan Edukasi Pencegahan Komplikasi Hipertensi (Cipete Selatan)",
    "Pembentukan Agent of Change (AoC) (Cipete Selatan)",
    "Pembinaan Agent of Change (AoC) (Cipete Selatan)",
    "Pembentukan Agent of Change (AoC) (Lebak Bulus)",
    "Pembinaan Agent of Change (AoC) (Lebak Bulus)",
    "Pembentukan Agent of Change (aoC) (Cilandak Barat)",
    "Pembinaan Agent of Change (AoC) (Cilandak Barat)",
    "Pembentukan Agent of Change (AoC) (Gandaria Selatan)",
    "Pembinaan Agent of Change (AoC) (Gandaria Selatan)",
    "Pembentukan Agent of Change (AoC) (Pondok Labu)",
    "Pembinaan Agent of Change (AoC) (Pondok Labu)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Lebak Bulus)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Pondok Labu)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Cilandak Barat)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Cipete Selatan)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Gandaria Selatan)"
  ];
  