export const optionsTugas = [
    "Puskesmas Cilandak",
    "PUSTU Pondok Labu",
    "PUSTU Cilandak Barat",
    "PUSTU Lebak Bulus",
    "PUSTU Gandaria Selatan",
    "PUSTU Cipete Selatan",
  ];

  export const optionBulanPelaksanaan = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
  ]
  
  export const optionPokja = ["Admen", "UKP", "UKM"];
  export const optionKegiatan = [
    "Peningkatan Pelayanan BLUD",
    "Penyediaan Layanan Kesehatan untuk UKP Rujukan, UKM dan UKM Rujukan Tingkat Daerah Provinsi",
    "Pengelolaan Pelayanan Kesehatan Dasar Melalui Pendekatan KeluargaPenyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota",
    "Perencanaan Kebutuhan dan Pendayagunaan Sumber Daya Manusia Kesehatan untuk UKP dan UKM di Wilayah Kabupaten/Kota",
    "Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM) Tingkat Daerah Kabupaten/Kota",
  ];
  export const optionSubKegiatan = [
    "Pelayanan dan Penunjang Pelayanan BLUD",
    "Pembinaan Pelaksanaan Upaya Pelayanan Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Dasar Melalui Pendekatan Keluarga",
    "Pengelolaan Pelayanan Kesehatan Ibu Hamil",
    "Pengelolaan Pelayanan Kesehatan Ibu Bersalin",
    "Pengelolaan Pelayanan Kesehatan Bayi Baru Lahir",
    "Pengelolaan Pelayanan Kesehatan Balita",
    "Pengelolaan Pelayanan Kesehatan pada Usia Pendidikan Dasar",
    "Pengelolaan Pelayanan Kesehatan pada Usia Produktif",
    "Pengelolaan Pelayanan Kesehatan pada Usia Lanjut",
    "Pengelolaan Pelayanan Kesehatan Penderita Hipertensi",
    "Pengelolaan Pelayanan Kesehatan Penderita Diabetes Melitus",
    "Pengelolaan Pelayanan Kesehatan Orang dengan Gangguan Jiwa Berat",
    "Pengelolaan Pelayanan Kesehatan Orang Terduga Tuberkulosis",
    "Pengelolaan Pelayanan Kesehatan Orang dengan Risiko Terinfeksi HIV",
    "Pengelolaan Pelayanan Kesehatan Gizi Masyarakat",
    "Pengelolaan Pelayanan Kesehatan Kerja dan Olahraga",
    "Pengelolaan Pelayanan Kesehatan Lingkungan",
    "Pengelolaan Pelayanan Promosi Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Tradisonal, Akupuntur, Asuhan Mandiri dan Tradisional Lainnya",
    "Pengelolaan Surveilans Kesehatan",
    "Pengelolaan Pelayanan Kesehatan Penyakit Menular dan Tidak Menular",
    "Pengelolaan pelayanan kesehatan orang dengan Tuberkulosis",
    "Pengelolaan pelayanan kesehatan orang dengan HIV (ODHIV)",
    "Pengelolaan pelayanan kesehatan Malaria",
    "Pengelolaan Kawasan tanpa rokok",
    "Pengelolaan Pelayanan Kesehatan Haji",
    "Pemenuhan Kebutuhan Sumber Daya Manusia Kesehatan Sesuai Standar",
    "Bimbingan Teknis dan Supervisi Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM)",
  ];
  export const optionKomponen = ["Makan", "Snack", "Transport", "honor"];
  export const optionIndikatorKinerja = [
    "Jumlah  Alat  Kesehatan/Alat  Penunjang  Medik Fasilitas Layanan Kesehatan yang Disediakan",
    "Jumlah  Alat  Kesehatan/Alat  Penunjang  Medik Fasilitas   Layanan   Kesehatan   yang   Terpelihara Sesuai Standar",
    "Jumlah Sarana, Prasarana dan Alat Kesehatan yang Telah Dilakukan Rehabilitasi dan Pemeliharaan Oleh Puskesmas",
    "Jumlah Ibu Hamil yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Ibu Bersalin yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Bayi Baru Lahir yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Balita yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Anak Usia Pendidikan Dasar yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penduduk Usia Produktif yangMendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penduduk Usia Lanjut yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penderita Hipertensi yang Mendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Penderita Diabetes Melitus yangMendapatkan Pelayanan Kesehatan Sesuai Standar",
    "Jumlah Orang yang Mendapatkan PelayananKesehatan Orang dengan Gangguan Jiwa Berat Sesuai Standar",
    "Jumlah Orang Terduga Menderita Tuberkulosis yang Mendapatkan Pelayanan Sesuai Standar",
    "Jumlah Orang Terduga Menderita HIV yang Mendapatkan Pelayanan Sesuai Standar",
    "Jumlah Fasilitas Kesehatan yang Terakreditasi diKabupaten/Kota",
    "Jumlah Dokumen Hasil Pengelolaan Sistem Informasi Kesehatan",
    "Jumlah Sumber Daya Manusia Kesehatan Kompetensi dan Kualifikasi Meningkat",
    "Jumlah Sumber Daya Manusia Kesehatan yang Memenuhi Standar di Fasilitas Pelayanan Kesehatan (Fasyankes)",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Perizinan Apotek, Toko Obat, Toko Alat Kesehatan, dan Optikal, Usaha Mikro ObatTradisional (UMOT)",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Sertifikat Produksi Pangan Industri Rumah Tangga dan Nomor P-IRT sebagai Izin Produksi, untuk Produk Makanan Minuman Tertentu yang Dapat Diproduksi oleh Industri Rumah Tangga",
    "Jumlah Dokumen Hasil Pengendalian dan Pengawasan serta Tindak Lanjut Pengawasan Penerbitan Sertifikat Laik Higiene Sanitasi Tempat Pengelolaan Makanan (TPM) antara lain Jasa Boga, Rumah Makan/Restoran dan Depot Air Minum (DAM)",
    "Jumlah Dokumen Hasil Bimbingan Teknis dan Supervisi Upaya Kesehatan Bersumber Daya Masyarakat (UKBM)",
    "Jumlah Dokumen Perencanaan Perangkat Daerah",
    "Jumlah Laporan Evaluasi Kinerja Perangkat Daerah",
    "Jumlah Laporan Keuangan Akhir Tahun SKPD dan Laporan Hasil Koordinasi Penyusunan Laporan Keuangan Akhir Tahun SKPD",
    "Jumlah Pegawai Berdasarkan Tugas dan Fungsi yang Mengikuti Pendidikan dan Pelatihan",
    "Jumlah Paket Peralatan dan Perlengkapan Kantoryang Disediakan",
    "Jumlah Paket Barang Cetakan dan Penggandaan yang Disediakan",
    "Jumlah Paket Bahan/Material yang Disediakan",
    "Jumlah Laporan Fasilitasi Kunjungan Tamu",
    "Jumlah Laporan Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD",
    "Jumlah Laporan Penyediaan Jasa Komunikasi, Sumber Daya Air dan Listrik yang Disediakan",
    "Jumlah Laporan Penyediaan Jasa Peralatan danPerlengkapan Kantor yang Disediakan",
    "Jumlah Laporan Penyediaan Jasa PelayananUmum Kantor yang Disediakan",
    "Jumlah Kendaraan Dinas Operasional atau Lapangan yang Dipelihara dan Dibayarkan Pajak dan Perizinannya",
    "Jumlah Peralatan dan Mesin Lainnya yang Dipelihara",
    "Jumlah BLUD yang Menyediakan Pelayanan dan Penunjang Pelayanan",
    "Jumlah Dokumen Hasil Pengelolaan Pelayanan Kesehatan Lingkungan"
  ];
  export const optionSumberPembiayaan = ["APBD", "BLUD"];

  export const optionAktivitas = [
    "Belanja Barang dan Jasa BLUD",
    "Belanja Modal Peralatan dan Mesin BLUD",
    "Belanja Modal Gedung dan Bangunan BLUD",
    "Sosialisasi Internal Puskesmas dan Pustu tentang Integrasi Pelayanan Kesehatan Primer (ILP)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Gandaria Selatan)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Cipete Selatan)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Cilandak Barat)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Lebak Bulus)",
    "Sosialisasi Internal Kader Posyandu dan Pokja Posyandu (Pondok Labu)",
    "Jejaring Fasyankes",
    "Peningkatan IKS di Wilayah Prioritas (Gandaria Selatan)",
    "Peningkatan IKS di Wilayah Prioritas (Cipete Selatan)",
    "Peningkatan IKS di Wilayah Prioritas (Cilandak Barat)",
    "Peningkatan IKS di Wilayah Prioritas (Lebak Bulus)",
    "Peningkatan IKS di Wilayah Prioritas (Pondok Labu)",
    "Optimalisasi Pelaksanaan KTR di Wilayah Kampung bebas Asap Rokok Kecamatan Cilandak",
    "Penyediaan Buku KIA",
    "Kelas Ibu Hamil (Gandaria Selatan)",
    "Kelas Ibu Hamil (Cipete Selatan)",
    "Kelas Ibu Hamil (Cilandak Barat)",
    "Kelas Ibu Hamil Luwes (Lebak Bulus)",
    "Kelas Ibu Hamil (Pondok Labu)",
    "Kelas Ibu Hamil Cemerlang (Gandaria Selatan)",
    "Kelas Ibu Hamil Cemerlang (Pondok Labu)",
    "Kelas Ibu Hamil Cemerlang (Cipete Selatan)",
    "Kelas Ibu Hamil Cemerlang (Cilandak Barat)",
    "Kelas Ibu Hamil Cemerlang (Lebak Bulus)",
    "Kelas Ibu Hamil (Puskesmas Cilandak)",
    "Supervisi Fasilitatif Fasyankes KIA (Gandaria Selatan)",
    "Supervisi Fasilitatif Fasyankes KIA (Cipete Selatan)",
    "Supervisi Fasilitatif Fasyankes KIA (Cilandak Barat)",
    "Supervisi Fasilitatif Fasyankes KIA (Lebak Bulus)",
    "Supervisi Fasilitatif Fasyankes KIA (Pondok Labu)",
    "Peningkatan Kemampuan dalam Menangani Kegawatdaruratan di RB",
    "Kelas Persiapan Persalinan dan Tour Rumah Bersalin",
    "Audit Kematian Maternal Perinatal",
    "Pemeriksaan Skrining Hipotiroid Kongenital (SHK)",
    "Refreshing Wawasan SDIDTK pada Kader Posyandu (Pondok Labu)",
    "Kelas Balita Disabilitas",
    "Pedas (Pengasuh Cerdas) (Lebak Bulus)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Gandaria Selatan)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Cipete Selatan)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Cilandak Barat)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Pondok Labu)",
    "Pelatihan Pikumbang bagi Guru PAUD dan TK (Lebak Bulus)",
    "Kelas Ibu Balita (Gandaria Selatan)",
    "Kelas Ibu Balita (Cipete Selatan)",
    "Kelas Ibu Balita (Lebak Bulus)",
    "Kelas Ibu Balita (Cilandak Barat)",
    "Rapat Koordinasi Kegiatan Pikumbang kepada Kepala Sekolah PAUD Wilayah Cilandak",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Cipete Selatan)",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Cilandak Barat)",
    "Peningkatan Kesehatan Kepada Anak Berkebutuhan Khusus (SLB) (Lebak Bulus)",
    "Roadshow Kesehatan Mental pada Remaja (Gandaria Selatan)",
    "Roadshow Kesehatan Mental pada Remaja (Cipete Selatan)",
    "Roadshow Kesehatan Mental pada Remaja (Lebak Bulus)",
    "Roadshow Kesehatan Mental pada Remaja (Cilandak Barat)",
    "Roadshow Kesehatan Mental pada Remaja (Pondok Labu)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Gandaria Selatan)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Cipete Selatan)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Cilandak Barat)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Lebak Bulus)",
    "Pelantikan Kader Kesehatan Remaja, Dokter Kecil dan Dokter Gigi Kecil (Pondok Labu)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Gandaria Selatan)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Cipete Selatan)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Cilandak Barat)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Lebak Bulus)",
    "Pertemuan Koordinasi Guru dengan Puskesmas (Pondok Labu)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Lebak Bulus)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Cilandak Barat)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Gandaria Selatan)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Cipete Selatan)",
    "Pelatihan Dokter Kecil / Kader Kesehatan Remaja (Pondok Labu)",
    "Pelatihan Konselor Sebaya (Cipete Selatan)",
    "Sosialisasi Deteksi Dini Kanker Anak (Cipete Selatan)",
    "Peningkatan Wawasan tentang KBPP (Cipete Selatan)",
    "Peningkatan Wawasan tentang KBPP (Cilandak Barat)",
    "Peningkatan Wawasan tentang KBPP (Pondok Labu)",
    "Peningkatan Wawasan tentang KBPP (Lebak Bulus)",
    "Monitoring evaluasi posyandu remaja (Cipete Selatan)",
    "Peningkatan Wawasan tentang Anemia Remaja Putri, Cara Penanggulangannya, dan Program Tablet Tambah D (Lebak Bulus)",
    "Peningkatan Wawasan tentang Anemia Remaja Putri (Pondok Labu)",
    "Pembelian Strip Gula Darah",
    "Sosialisasi SKILAS dan PJP (Lebak Bulus)",
    "Sosialisasi SKILAS dan PJP (Pondok Labu)",
    "Sosialisasi SKILAS dan PJP (Cilandak Barat)",
    "Sosialisasi SKILAS dan PJP (Cipete Selatan)",
    "Sosialisasi SKILAS dan PJP (Gandaria Selatan)",
    "Peningkatan wawasan lansia \"Pencegahan Dementia pada lansia dengan senam otak\" (Lebak Bulus)",
    "Sosialisasi kader tentang caregriver (Cipete Selatan)",
    "Pelatihan Perawatan Jangka Panjang Bagi Caregiver (Puskesmas Cilandak)",
    "Konseling Jiwa Pada Lansia dengan Gangguan Depresi (Puskesmas Cilandak)",
    "Pembelian Strip Kolestrol",
    "Peningkatan Wawasan Edukasi Pencegahan Komplikasi Hipertensi (Cipete Selatan)",
    "Pembentukan Agent of Change (AoC) (Cipete Selatan)",
    "Pembinaan Agent of Change (AoC) (Cipete Selatan)",
    "Pembentukan Agent of Change (AoC) (Lebak Bulus)",
    "Pembinaan Agent of Change (AoC) (Lebak Bulus)",
    "Pembentukan Agent of Change (aoC) (Cilandak Barat)",
    "Pembinaan Agent of Change (AoC) (Cilandak Barat)",
    "Pembentukan Agent of Change (AoC) (Gandaria Selatan)",
    "Pembinaan Agent of Change (AoC) (Gandaria Selatan)",
    "Pembentukan Agent of Change (AoC) (Pondok Labu)",
    "Pembinaan Agent of Change (AoC) (Pondok Labu)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Lebak Bulus)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Pondok Labu)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Cilandak Barat)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Cipete Selatan)",
    "Sosialisasi Integrasi Layanan Primer (ILP) dan Penginputan skrining PTM di Aplikasi Sehat Indonesiaku (Gandaria Selatan)",
    "Refreshing Kader Posbindu Terkait Penggunaan Alat Posbindu (Cipete Selatan)",
    "Peningkatan Wawasan Edukasi Pencegahan Komplikasi Diabetes Mellitus (Cipete Selatan)",
    "Refreshing Kader Posbindu Terkait Penggunaan Alat Posbindu (Pondok Labu)",
"Peningkatan Wawasan Penanganan ODGJ kepada Lintas Sektoral dan Masyarakat (Gandaria Selatan)",
"Peningkatan Wawasan Penanganan ODGJ kepada Lintas Sektoral dan Masyarakat (Cipete Selatan)",
"Rehabilitasi Berbasis Masyarakat (Terapi Aktivitas Kelompok)(Cilandak Barat)",
"Rehabilitasi Berbasis Masyarakat (Terapi Aktivitas Kelompok)(Lebak Bulus)",
"Rehabilitasi Berbasis Masyarakat (Terapi Aktivitas Kelompok)(Pondok Labu)",
"Penyuluhan Kesehatan tentang Pentingnya Skrining Kesehatan Jiwa terkait Gangguan Depresi dan Ansietas (Cipete Selatan)",
"Penyuluhan Kesehatan tentang Pentingnya Skrining Kesehatan Jiwa terkait Gangguan Depresi dan Ansietas (Cilandak Barat)",
"Pertemuan Kelompok Dukungan Keluarga ODGJ (Terapi Aktifitas Kelompok) (Cipete Selatan)",
"Rehabilitasi Berbasis Masyarakat (Terapi Aktivitas Kelompok)(Gandaria Selatan)",
"Peningkatan Wawasan tentang Perilaku Menyimpang pada Remaja (Pondok Labu)",
"Refreshing Kader TB (Puskesmas Cilandak)",
"Rapat Koordinasi Pelayanan Program Penanggulanan TB (Puskesmas Cilandak)",
"Peningkatan Pengetahuan tentang TBC ke Keluarga Pasien TBC (Gandaria Selatan)",
"Peningkatan Pengetahuan Tentang TBC ke Keluarga Pasien TBC (Cipete Selatan)",
"Peningkatan Pengetahuan tentang TBC ke Keluarga Pasien TBC (Cilandak Barat)",
"Peningkatan Pengetahuan tentang TBC ke Keluarga Pasien TBC (Lebak Bulus)",
"Peningkatan Pengetahuan tentang TBC ke Keluarga Pasien TBC (Pondok Labu)",
"Grebeg TB (Gandaria Selatan)",
"Grebeg TB (Cipete Selatan)",
"Grebeg TB (Cilandak Barat)",
"Grebeg TB (Lebak Bulus)",
"Grebeg TB (Pondok Labu)",
"Sosialisasi Tatalaksana Terduga TBC dengan Metode Skrining",
"Peningkatan Wawasan HIV/AIDS melalui ABAT (Gandaria Selatan)",
"Peningkatan Wawasan HIV/AIDS melalui ABAT (Cipete Selatan)",
"Peningkatan Wawasan HIV/AIDS melalui ABAT (Cilandak Barat)",
"Peningkatan Wawasan HIV/AIDS melalui ABAT (Lebak Bulus)",
"Peningkatan Wawasan HIV/AIDS melalui ABAT (Pondok Labu)",
"Pertemuan Pengguna NAPZA Suntik",
"Mobile VCT Populasi Kunci",
"Orientasi Kegiatan KPG Umma Beraksi itu Penting (Gandaria Selatan)",
"Orientasi Kegiatan KPG Umma Beraksi itu Penting (Pondok Labu)",
"Orientasi Kegiatan KPG Umma Berakzi Itu Penting dengan GEMA PARENTING (Cilandak Barat)",
"Orientasi Kegiatan KPG Umma Berakzi Itu Penting (Lebak Bulus)",
"Orientasi Kegiatan KPG Umma Berakzi Itu Penting dengan CINTA SI BOCIL (Cipete Selatan)",
"Monitoring Kegiatan KPG Umma Beraksi itu Penting (Gandaria Selatan)",
"Monitoring Kegiatan KPG Umma Berakzi Itu Penting dengan GEMA PARENTING (Cilandak Barat)",
"Monitoring Kegiatan KPG Umma Berakzi Itu Penting (Lebak Bulus)",
"Monitoring Kegiatan KPG Umma Berakzi Itu Penting dengan CINTA SI BOCIL (Cipete Selatan)",
"Evaluasi Kegiatan KPG Umma Beraksi itu Penting (Gandaria Selatan)",
"Evaluasi Kegiatan KPG Umma Berakzi Itu Penting dengan GEMA PARENTING (Cilandak Barat)",
"Evaluasi Kegiatan KPG Umma Berakzi Itu Penting (Lebak Bulus)",
"Evaluasi Kegiatan KPG Umma Berakzi Itu Penting dengan CINTA SI BOCIL (Cipete Selatan)",
"Peningkatan Wawasan tentang Anemia Remaja Putri dan Cara Penanggulangannya (Gandaria Selatan)",
"Peningkatan Wawasan tentang Anemia Remaja Putri dan Cara Penanggulangannya (Cipete Selatan)",
"Peningkatan Wawasan tentang Anemia Remaja Putri dan Cara Penanggulangannya (Cilandak Barat)",
"Peningkatan Wawasan tentang Anemia Remaja Putri dan Cara Penanggulangannya (Lebak Bulus)",
"Peningkatan Wawasan tentang Anemia Remaja Putri dan Cara Penanggulangannya (Pondok Labu)",
"Sosialisasi tentang PMBA (Cipete Selatan)",
"Monitoring dan Evaluasi Konvergensi Stunting Kecamatan Cilandak Tahun 2025",
"Sosialisasi dan Persiapan KPG Umma Berakzi Itu Penting",
"Pendampingan Umma Berakzi Itu Penting dengan GEMA PARENTING (Cilandak Barat)",
"Pendampingan Umma Berakzi Itu Penting dengan KOMPAS (Pondok Labu)",
"Pendampingan Umma Berakzi Itu Penting dengan GEN PEDAS (Lebak Bulus)",
"Pendampingan Umma Berakzi Itu Penting dengan CINTA SI BOCIL (Cipete Selatan)",
"Pendampingan Umma Beraksi itu Penting (Gandaria Selatan)",
"Monitoring Kegiatan KPG Umma Berakzi itu Penting (Pondok Labu)",
"Evaluasi Kegiatan KPG Umma Berakzi itu Penting (Pondok Labu)",
"Sosialisasi tentang PMBA (Lebak Bulus)",
"Pengadaan Pemberian Makanan Tambahan (PMT) Pemulihan Pada Ibu Hamil KEK",
"Pengadaan Pemberian Makanan Tambahan (PMT) Pemulihan pada Balita dengan Weight Faltering",
"Pengadaan Pemberian Makanan Tambahan (PMT) Pemulihan pada Balita dengan Underweight",
"Pengadaan Pemberian Makanan Tambahan (PMT) Pemulihan pada Balita dengan Gizi Kurang",
"Pengadaan Pemberian Makanan Tambahan (PMT) Pemulihan pada Balita dengan Gizi Buruk",
"Pengadaan Alat dan Bahan Skrining Anemia Remaja Putri Kelas 9 dan 12",
"Pengadaan Alat dan Bahan Skrining Anemia Remaja Putri Kelas 7 dan 10",
"Pembinaan Pos UKK (Gandaria Selatan)",
"Pembinaan Pos UKK (Cipete Selatan)",
"Pembinaan Pos UKK (Cilandak Barat)",
"Pembinaan Pos UKK  (Pondok Labu)",
"Pembinaan Pos UKK  (Lebak Bulus)",
"Pengukuran Kebugaran Anak Sekolah (Gandaria Selatan)",
"Pengukuran Kebugaran Anak Sekolah (Cipete Selatan)",
"Pengukuran Kebugaran Anak Sekolah (Cilandak Barat)",
"Pengukuran Kebugaran Anak Sekolah (Lebak Bulus)",
"Pengukuran Kebugaran Anak Sekolah (Pustu Pondok Labu)",
"Pengukuran Kebugaran pada SKPD /UKPD Pemprov DKI (se Kecamatan Cilandak)",
"Pengukuran Kebugaran Pegawai Puskesmas (se Puskesmas Cilandak)",
"Simulasi Keadaan Bencana (Puskesmas Cilandak)",
"Peningkatan Wawasan Mengenai Penanganan Cedera Olahraga (Puskesmas Cilandak)",
"Latihan Rutin Kelompok Olahraga Pegawai Puskesmas",
"Pemicuan STBM (Gandaria Selatan)",
"Pemicuan STBM (Lebak Bulus)",
"Pemicuan STBM (Cilandak Barat)",
"Pemicuan STBM (Pondok Labu)",
"Pemicuan STBM (Cipete Selatan)",
"Peningkatan Wawasan Terkait STBM ke Lintas Sektor",
"Verifikasi STBM (Cipete Selatan)",
"Verifikasi STBM (Cilandak Barat)",
"Verifikasi STBM (Pondok Labu)",
"Sosialisasi dan Penggalangan Komitmen STBM Pilar 1 Bagi Pemilik Kontrakan/Kost",
"Peningkatan Wawasan Kantin Sekolah Sehat",
"Jasa Pengelolaan Limbah Medis",
"Peningkatan Wawasan Higiene Sanitasi Pangan bagi penjamah pangan TPP (Restoran, Jasa boga, DAMIU)",
"Jasa Pemeriksaan Sampel Air Minum Warga",
"Jasa Pemeriksaan Sampel Air Minum Instalasi Pengolahan Air (IPA) Cilandak",
"Sanitarian Kit",
"Gerakan Makan Buah Bersama (Puskesmas Cilandak)",
"Gerakan Makan Buah Bersama (Gandaria Selatan)",
"Gerakan Makan Buah Bersama (Cipete Selatan)",
"Gerakan Makan Buah Bersama (Cilandak Barat)",
"Gerakan Makan Buah Bersama (Lebak Bulus)",
"Gerakan Makan Buah Bersama (Pondok Labu)",
"Peringatan Hari Kesehatan Tahun 2025",
"Orientasi tentang Kompetensi Dasar bagi Posyandu (Gandaria Selatan)",
"Orientasi tentang Kompetensi Dasar bagi Posyandu (Cipete Selatan)",
"Orientasi tentang Kompetensi Dasar bagi Posyandu (Cilandak Barat)",
"Orientasi tentang Kompetensi Dasar bagi Posyandu (Lebak Bulus)",
"Orientasi tentang Kompetensi Dasar bagi Posyandu (Pondok Labu)",
"Orientasi KAP bagi Kader dalam Penanggulangan Stunting",
"Gerakan Makan Protein Hewani (Puskesmas Cilandak)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Gandaria Selatan)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Cipete Selatan)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Cilandak Barat)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Lebak Bulus)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Pondok Labu)",
"Pertemuan Survey Mawas Diri (SMD) dan Musyawarah Masyarakat Desa (MMD) (Puskesmas Cilandak)",
"Pemberdayaan Masyarakat dalam Penyuluhan Kelompok (Gandaria Selatan)",
"Pemberdayaan Masyarakat dalam Penyuluhan Kelompok (Cipete Selatan)",
"Pemberdayaan Masyarakat dalam Penyuluhan Kelompok (Cilandak Barat)",
"Pemberdayaan Masyarakat dalam Penyuluhan Kelompok",
"Pemberdayaan Masyarakat dalam Penyuluhan Kelompok",
"Kampanye Germas di UKPD (Gandaria Selatan)",
"Kampanye Germas di UKPD (Cipete Selatan)",
"Kampanye Germas di UKPD (Cilandak Barat)",
"Kampanye Germas di UKPD (Lebak Bulus)",
"Kampanye Germas di UKPD (Pondok Labu)",
"Pendampingan UKBM (Gandaria Selatan)",
"Pendampingan UKBM (Cipete Selatan)",
"Pendampingan UKBM (Cilandak Barat)",
"Pendampingan UKBM (Lebak Bulus)",
"Pendampingan UKBM (Pondok Labu)",
"Refreshing Kader Asman Toga (sePuskesmas Kec Cilandak)",
"Pemanfaatan dan Pemeliharaan TOGA (Gandaria Selatan)",
"Pemanfaatan dan Pemeliharaan TOGA (Cilandak Barat)",
"Pemanfaatan dan Pemeliharaan TOGA (Lebak Bulus)",
"Pemanfaatan dan Pemeliharaan TOGA (Pondok Labu)",
"Refreshing Kader Asman Toga (Cipete Selatan)",
"Logistik pengambilan spesimen potensi KLB",
"Evaluasi dan Monitoring Kader Cilandak Cepat Tanggap Surveilans (CCTV)",
"Peningkatan Kapasitas Kader CCTV Terkait Penyakit Menular",
"Sosialisasi Deteksi Dini Kanker Anak (Gandaria Selatan)",
"Sosialisasi Deteksi Dini Kanker Anak (Cipete Selatan)",
"Sosialisasi Deteksi Dini Kanker Anak (Cilandak Barat)",
"Sosialisasi Deteksi Dini Kanker Anak (Lebak Bulus)",
"Sosialisasi Deteksi Dini Kanker Anak (Pondok Labu)",
"Road Show dalam Rangka Pekan Imunisasi Dunia",
"Evaluasi Kader Jumantik Tahunan",
"Deteksi Dini PTM Usia 10-18 Tahun",
"Sosialisasi Microplaning Imunisasi Dasar dan Lanjutan",
"Peningkatan Wawasan pada Masyarakat tentang ISPA dan Diare (Cilandak Barat)",
"Workshop Evaluasi Kader Jumantik (Cilandak Barat)",
"Workshop Evaluasi Kader Jumantik (Pondok Labu)",
"Workshop Evaluasi Kader Jumantik (Cipete Selatan)",
"Workshop Evaluasi Kader Jumantik (Gandaria Selatan)",
"Workshop Evaluasi Kader Jumantik (Lebak Bulus)",
"Deteksi Dini PTM Usia 10-18 Tahun (Gandaria Selatan)",
"Peningkatan Wawasan pada Masyarakat tentang ISPA dan Diare (Lebak Bulus)",
"Peningkatan Wawasan pada Masyarakat tentang ISPA dan Diare (Cipete Selatan)",
"Peningkatan wawasan kader kesehatan remaja tentang kesehatan reproduksi (Lebak Bulus)",
"Monitoring Evaluasi Posyandu Remaja (Cilandak Barat)",
"Pembentukan Kampung Bebas Jentik (KBJ) (Gandaria Selatan)",
"Pembentukan Kampung Bebas Jentik (KBJ) (Cipete Selatan)",
"Pembentukan Kampung Bebas Jentik (KBJ) (Cilandak Barat)",
"Pembentukan Kampung Bebas Jentik (KBJ) (Lebak Bulus)",
"Pembentukan Kampung Bebas Jentik (KBJ) (Pondok Labu)",
"Peningkatan Wawasan terkait DBD pada 7 Tatanan (Gandaria Selatan)",
"Peningkatan Wawasan terkait DBD pada 7 Tatanan (Cipete Selatan)",
"Peningkatan Wawasan terkait DBD pada 7 Tatanan (Cilandak Barat)",
"Peningkatan Wawasan terkait DBD pada 7 Tatanan (Lebak Bulus)",
"Peningkatan Wawasan terkait DBD pada 7 Tatanan (Pondok Labu)",
"Pembentukan Jumantik Sekolah (Gandaria Selatan)",
"Pembentukan Jumantik Sekolah Menengah dan Atas (Gandaria Selatan)",
"Penguatan Program Demam Berdarah",
"Tinjau TB Sensitif Obat (Puskesmas Cilandak)",
"Pengadaan PMT Pasien TB",
"MICA TB RO (Monthly Interim Cohort Analysis TB Resisten Obat) (Puskesmas Cilandak)",
"Pertemuan KDS",
"Pemeriksaan Lab CD4",
"Pemeriksaan Viral Load HIV",
"Peningkatan Wawasan Penemuan Kasus Malaria Bagi Kader Kesehatan di Wilayah",
"Peningkatan wawasan pelajar dampak merokok bagi kesehatan",
"Pengadaan Spirometri",
"Sosialisasi Pembentukan Kawasan Tanpa Rokok di Sekolah",
"Peningkatan Wawasan tentang Kesehatan Calon Jemaah Haji",
"Pengukuran Kebugaran Calon Jemaah Haji",
"Gaji Pegawai Non PNS",
"TKD Pegawai Non PNS",
"Pembinaan Kader Posyandu Bidang Layanan Kesehatan Jambore Kader",
"Minilokakarya Lintas Sektoral Puskesmas Cillandak",
"Rapat Koordinasi Kesehatan Puskesmas Pembantu (Gandaria Selatan)",
"Rapat Koordinasi Kesehatan Puskesmas Pembantu (Cipete Selatan)",
"Rapat Koordinasi Kesehatan Puskesmas Pembantu (Cilandak Barat)",
"Rapat Koordinasi Kesehatan Puskesmas Pembantu (Lebak Bulus)",
"Rapat Koordinasi Kesehatan Puskesmas Pembantu (Pondok Labu)",
  ];
  